const poemData = [
    { text: "人", py: "rén", zh: "有一个人。", en: "There was a man" },
    { text: "有", py: "yǒu", zh: "有。", en: "who" },
    { text: "亡", py: "wáng", zh: "动词，丢失，失去。", en: "lost", exam: true },
    { text: "斧", py: "fǔ", zh: "斧头。", en: "an axe." },
    { text: "者", py: "zhě", zh: "……的人。", en: "The person" },
    { text: "，", punc: true },
    { text: "意", py: "yì", zh: "动词，怀疑，猜忌（古汉语中常用义）。", en: "suspected", exam: true },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "邻人", py: "lín rén", zh: "邻居。", en: "neighbor's" },
    { text: "之", py: "zhī", zh: "的。", en: "的" },
    { text: "子", py: "zǐ", zh: "儿子。", en: "son:" },
    { text: "：", punc: true },
    { text: "视", py: "shì", zh: "动词，观察，看。", en: "looking at", exam: true },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "行步", py: "xíng bù", zh: "走路的姿势、步伐。", en: "way of walking," },
    { text: "，", punc: true },
    { text: "窃", py: "qiè", zh: "动词，偷盗，偷窃。", en: "he seemed to have stolen" },
    { text: "斧", py: "fǔ", zh: "斧头。", en: "the axe;" },
    { text: "也", py: "yě", zh: "语气助词，表判断陈述。", en: "(particle)" },
    { text: "；", punc: true },
    { text: "颜色", py: "yán sè", zh: "古今异义词，指脸上的神色、面部表情。", en: "his facial expression", exam: true },
    { text: "，", punc: true },
    { text: "窃", py: "qiè", zh: "偷盗。", en: "looked like he stole" },
    { text: "斧", py: "fǔ", zh: "斧头。", en: "the axe;" },
    { text: "也", py: "yě", zh: "也。", en: "(particle)" },
    { text: "；", punc: true },
    { text: "言语", py: "yán yǔ", zh: "说话的声音和语气。", en: "his words and speech" },
    { text: "，", punc: true },
    { text: "窃", py: "qiè", zh: "偷盗。", en: "sounded like he stole" },
    { text: "斧", py: "fǔ", zh: "斧头。", en: "the axe;" },
    { text: "也", py: "yě", zh: "也。", en: "(particle)" },
    { text: "；", punc: true },
    { text: "动作态度", py: "dòng zuò tài dù", zh: "一举一动，举手投足的表现。", en: "his every action and demeanor," },
    { text: "无为而不", py: "wú wéi ér bù", zh: "双重否定词组，没有什么表现不……，也就是说“全身上下无一不像”。", en: "there was nothing that did not suggest he", exam: true },
    { text: "窃", py: "qiè", zh: "偷盗。", en: "stole" },
    { text: "斧", py: "fǔ", zh: "斧头。", en: "the axe." },
    { text: "者", py: "zhě", zh: "的特征。", en: "(particle)" },
    { text: "也", py: "yě", zh: "呀。", en: "(particle)" },
    { text: "。", punc: true },
    { text: "俄而", py: "é ér", zh: "时间副词，一会儿，不久，转眼间。", en: "Soon afterwards,", exam: true },
    { text: "掘", py: "jué", zh: "动词，挖掘，挖开。", en: "while digging" },
    { text: "其", py: "qí", zh: "他自家的。", en: "his own" },
    { text: "沟", py: "gōu", zh: "水沟，地沟。", en: "ditch," },
    { text: "而", py: "ér", zh: "连词，表顺承，就。", en: "he" },
    { text: "得", py: "dé", zh: "找到，得到。", en: "found" },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "斧", py: "fǔ", zh: "斧头。", en: "axe." },
    { text: "，", punc: true },
    { text: "他日", py: "tā rì", zh: "名词，过了几天，重新有一天。", en: "Another day," },
    { text: "复", py: "fù", zh: "副词，再次，又。", en: "he again", exam: true },
    { text: "见", py: "jiàn", zh: "看见。", en: "saw" },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "邻人", py: "lín rén", zh: "邻居。", en: "neighbor's" },
    { text: "之", py: "zhī", zh: "的。", en: "的" },
    { text: "子", py: "zǐ", zh: "儿子。", en: "son," },
    { text: "，", punc: true },
    { text: "动作", py: "dòng zuò", zh: "言行举止。", en: "but his actions" },
    { text: "态度", py: "tài dù", zh: "神态举止。", en: "and demeanor" },
    { text: "皆", py: "jiē", zh: "副词，全，都。", en: "all" },
    { text: "无似", py: "wú sì", zh: "一点也不像。“无”，没有；“似”，像。", en: "looked nothing like someone who had", exam: true },
    { text: "窃", py: "qiè", zh: "偷盗。", en: "stole" },
    { text: "斧", py: "fǔ", zh: "斧头。", en: "the" },
    { text: "者", py: "zhě", zh: "的人。", en: "axe" },
    { text: "也", py: "yě", zh: "了。", en: "anymore." },
    { text: "。", punc: true }
];
